In [1]:
import pandas as pd

In [ ]:
df = pd.read_csv('atp.csv')
df

In [19]:
files = []
for i in range(2001,2013):
    files.append(str(i)+'.xls')
for i in range(2013,2023):
    files.append(str(i)+'.xlsx')
    
files

['2001.xls',
 '2002.xls',
 '2003.xls',
 '2004.xls',
 '2005.xls',
 '2006.xls',
 '2007.xls',
 '2008.xls',
 '2009.xls',
 '2010.xls',
 '2011.xls',
 '2012.xls',
 '2013.xlsx',
 '2014.xlsx',
 '2015.xlsx',
 '2016.xlsx',
 '2017.xlsx',
 '2018.xlsx',
 '2019.xlsx',
 '2020.xlsx',
 '2021.xlsx',
 '2022.xlsx']

In [22]:
for i in files:
    dfi = pd.read_excel(i)
    df = pd.concat([df, dfi])
    
df

C:\Users\abele\anaconda3\lib\site-packages\openpyxl\worksheet\_reader.py:312: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
C:\Users\abele\anaconda3\lib\site-packages\openpyxl\worksheet\_reader.py:312: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
C:\Users\abele\anaconda3\lib\site-packages\openpyxl\worksheet\_reader.py:312: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
C:\Users\abele\anaconda3\lib\site-packages\openpyxl\worksheet\_reader.py:312: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

,ATP,Location,Tournament,Date,Series,Court,Surface,Round,Best of,Winner,...,UBW,UBL,LBW,LBL,SJW,SJL,MaxW,MaxL,AvgW,AvgL
0,1,Adelaide,AAPT Championships,2001-01-01,International,Outdoor,Hard,1st Round,3.0,Clement A.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Adelaide,AAPT Championships,2001-01-01,International,Outdoor,Hard,1st Round,3.0,Goldstein P.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,Adelaide,AAPT Championships,2001-01-01,International,Outdoor,Hard,1st Round,3.0,Haas T.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,Adelaide,AAPT Championships,2001-01-01,International,Outdoor,Hard,1st Round,3.0,Henman T.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,Adelaide,AAPT Championships,2001-01-01,International,Outdoor,Hard,1st Round,3.0,Hewitt L.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2627,68,Turin,Masters Cup,2022-11-18,Masters Cup,Indoor,Hard,Round Robin,NaN,Djokovic N.,...,NaN,NaN,NaN,NaN,NaN,NaN,1.39,3.55,1.34,3.25
2628,68,Turin,Masters Cup,2022-11-18,Masters Cup,Indoor,Hard,Round Robin,NaN,Rublev A.,...,NaN,NaN,NaN,NaN,NaN,NaN,2.63,1.63,2.39,1.57
2629,68,Turin,Masters Cup,2022-11-19,Masters Cup,Indoor,Hard,Semifinals,NaN,Djokovic N.,...,NaN,NaN,NaN,NaN,NaN,NaN,1.28,4.75,1.23,4.14
2630,68,Turin,Masters Cup,2022-11-19,Masters Cup,Indoor,Hard,Semifinals,NaN,Ruud C.,...,NaN,NaN,NaN,NaN,NaN,NaN,2.35,1.75,2.18,1.69
2631,68,Turin,Masters Cup,2022-11-20,Masters Cup,Indoor,Hard,The Final,NaN,Djokovic N.,...,NaN,NaN,NaN,NaN,NaN,NaN,1.29,4.90,1.23,4.21

In [23]:
df.to_csv('atp.csv', index = False)

In [24]:
df.isnull().sum()

ATP               0
Location          0
Tournament        0
Date              0
Series            0
Court             0
Surface           0
Round             0
Best of          15
Winner            0
Loser             0
WRank            20
LRank           105
W1              319
L1              316
W2              883
L2              882
W3            32747
L3            32748
W4            55579
L4            55579
W5            59116
L5            59116
Wsets           288
Lsets           290
Comment           0
CBW           41437
CBL           41437
GBW           53746
GBL           53746
IWW           45444
IWL           45444
SBW           53924
SBL           53924
B365W          8704
B365L          8681
B&WW          60199
B&WL          60199
EXW           21885
EXL           21880
PSW           15000
PSL           15000
WPts          16208
LPts          16290
UBW           50625
UBL           50625
LBW           33165
LBL           33154
SJW           45724
SJL           45717
MaxW          29559
MaxL          29559
AvgW          29559
AvgL          29559
dtype: int64

In [7]:
df = pd.read_csv('atp.csv')
df

C:\Users\abele\AppData\Local\Temp\ipykernel_16856\1540220969.py:1: DtypeWarning: Columns (12,15,16,17,18,38) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('atp.csv')

,ATP,Location,Tournament,Date,Series,Court,Surface,Round,Best of,Winner,...,UBW,UBL,LBW,LBL,SJW,SJL,MaxW,MaxL,AvgW,AvgL
0,1,Adelaide,AAPT Championships,2001-01-01,International,Outdoor,Hard,1st Round,3.0,Clement A.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Adelaide,AAPT Championships,2001-01-01,International,Outdoor,Hard,1st Round,3.0,Goldstein P.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,Adelaide,AAPT Championships,2001-01-01,International,Outdoor,Hard,1st Round,3.0,Haas T.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,Adelaide,AAPT Championships,2001-01-01,International,Outdoor,Hard,1st Round,3.0,Henman T.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,Adelaide,AAPT Championships,2001-01-01,International,Outdoor,Hard,1st Round,3.0,Hewitt L.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61291,68,Turin,Masters Cup,2022-11-18,Masters Cup,Indoor,Hard,Round Robin,NaN,Djokovic N.,...,NaN,NaN,NaN,NaN,NaN,NaN,1.39,3.55,1.34,3.25
61292,68,Turin,Masters Cup,2022-11-18,Masters Cup,Indoor,Hard,Round Robin,NaN,Rublev A.,...,NaN,NaN,NaN,NaN,NaN,NaN,2.63,1.63,2.39,1.57
61293,68,Turin,Masters Cup,2022-11-19,Masters Cup,Indoor,Hard,Semifinals,NaN,Djokovic N.,...,NaN,NaN,NaN,NaN,NaN,NaN,1.28,4.75,1.23,4.14
61294,68,Turin,Masters Cup,2022-11-19,Masters Cup,Indoor,Hard,Semifinals,NaN,Ruud C.,...,NaN,NaN,NaN,NaN,NaN,NaN,2.35,1.75,2.18,1.69
61295,68,Turin,Masters Cup,2022-11-20,Masters Cup,Indoor,Hard,The Final,NaN,Djokovic N.,...,NaN,NaN,NaN,NaN,NaN,NaN,1.29,4.90,1.23,4.21

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61296 entries, 0 to 61295
Data columns (total 54 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ATP         61296 non-null  int64
 1   Location    61296 non-null  object
 2   Tournament  61296 non-null  object
 3   Date        61296 non-null  object
 4   Series      61296 non-null  object
 5   Court       61296 non-null  object
 6   Surface     61296 non-null  object
 7   Round       61296 non-null  object
 8   Best of     61281 non-null  float64
 9   Winner      61296 non-null  object
 10  Loser       61296 non-null  object
 11  WRank       61276 non-null  float64
 12  LRank       61191 non-null  object
 13  W1          60977 non-null  float64
 14  L1          60980 non-null  float64
 15  W2          60413 non-null  object
 16  L2          60414 non-null  object
 17  W3          28549 non-null  object
 18  L3          28548 non-null  object
 19  W4          5717 non-null   float64
 20  L4          5717 non-null   float64
 21  W5          2180 non-null   float64
 22  L5          2180 non-null   float64
 23  Wsets       61008 non-null  float64
 24  Lsets       61006 non-null  float64
 25  Comment     61296 non-null  object
 26  CBW         19859 non-null  float64
 27  CBL         19859 non-null  float64
 28  GBW         7550 non-null   float64
 29  GBL         7550 non-null   float64
 30  IWW         15852 non-null  float64
 31  IWL         15852 non-null  float64
 32  SBW         7372 non-null   float64
 33  SBL         7372 non-null   float64
 34  B365W       52592 non-null  float64
 35  B365L       52615 non-null  float64
 36  B&WW        1097 non-null   float64
 37  B&WL        1097 non-null   float64
 38  EXW         39411 non-null  object
 39  EXL         39416 non-null  float64
 40  PSW         46296 non-null  float64
 41  PSL         46296 non-null  float64
 42  WPts        45088 non-null  float64
 43  LPts        45006 non-null  float64
 44  UBW         10671 non-null  float64
 45  UBL         10671 non-null  float64
 46  LBW         28131 non-null  float64
 47  LBL         28142 non-null  float64
 48  SJW         15572 non-null  float64
 49  SJL         15579 non-null  float64
 50  MaxW        31737 non-null  float64
 51  MaxL        31737 non-null  float64
 52  AvgW        31737 non-null  float64
 53  AvgL        31737 non-null  float64
dtypes: float64(37), int64(1), object(16)
memory usage: 25.3+ MB

In [4]:
df.columns

Index(['ATP', 'Location', 'Tournament', 'Date', 'Series', 'Court', 'Surface',
       'Round', 'Best of', 'Winner', 'Loser', 'WRank', 'LRank', 'W1', 'L1',
       'W2', 'L2', 'W3', 'L3', 'W4', 'L4', 'W5', 'L5', 'Wsets', 'Lsets',
       'Comment', 'CBW', 'CBL', 'GBW', 'GBL', 'IWW', 'IWL', 'SBW', 'SBL',
       'B365W', 'B365L', 'B&WW', 'B&WL', 'EXW', 'EXL', 'PSW', 'PSL', 'WPts',
       'LPts', 'UBW', 'UBL', 'LBW', 'LBL', 'SJW', 'SJL', 'MaxW', 'MaxL',
       'AvgW', 'AvgL'],
      dtype='object')

In [8]:
# drop useless betting odds columns 
columns_to_drop = ['CBW', 'CBL', 'GBW', 'GBL', 'IWW', 'IWL', 'SBW', 'SBL', 
                   'B&WW', 'B&WL', 'EXW', 'EXL', 'PSW', 'PSL', 'WPts',
                   'LPts', 'UBW', 'UBL', 'LBW', 'LBL', 'SJW', 'SJL',
                   'MaxW', 'MaxL','AvgW', 'AvgL']

df = df.drop(columns = columns_to_drop)

In [10]:
df['Comment'].unique()

array(['Completed', 'Retired', 'Walkover', 'Disqualified', 'Awarded',
       'Sched', 'Rrtired'], dtype=object)

In [18]:
df = df[(df['Comment'] == 'Completed') | (df['Comment'] == 'Awarded')]
df = df.drop(df[df['B365W'].isnull()].index, axis = 0)
df = df.drop(df[df['LRank'].isnull()].index, axis = 0)
df = df.drop(df[df['WRank'].isnull()].index, axis = 0)
df = df.drop(df[df['Best of'].isnull()].index, axis = 0)
df = df.drop(df[df['W2'].isnull()].index, axis = 0)

In [36]:
df.isnull().sum()

ATP               0
Location          0
Tournament        0
Date              0
Series            0
Court             0
Surface           0
Round             0
Best of           0
Winner            0
Loser             0
WRank             0
LRank             0
W1                0
L1                0
W2                0
L2                0
W3            26247
L3            26247
W4            45627
L4            45627
W5            48661
L5            48661
Wsets             0
Lsets             0
Comment           0
B365W             0
B365L             0
dtype: int64